version: '3'
services:
  web:
    build: .
    ports:
     - "5001:5000"
  redis:
    image: redis:latest
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017